"""initial manager schema

Revision ID: 229a6edc0e40
Revises: 
Create Date: 2026-07-11 17:07:02.966185
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '229a6edc0e40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('details_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_resource_id'), 'audit_events', ['resource_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('workers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('capabilities_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('worker_version', sa.String(length=128), nullable=False),
    sa.Column('rvc_commit_hash', sa.String(length=64), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_job_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workers')),
    sa.UniqueConstraint('name', name=op.f('uq_workers_name')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_workers_token_hash'))
    )
    op.create_index(op.f('ix_workers_current_job_id'), 'workers', ['current_job_id'], unique=False)
    op.create_index(op.f('ix_workers_status'), 'workers', ['status'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('storage_uri', sa.String(length=2048), nullable=False),
    sa.Column('flat_storage_uri', sa.String(length=2048), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('quality_report_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_usable', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_datasets_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets'))
    )
    op.create_table('experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_experiments_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_experiments_dataset_id_datasets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_index(op.f('ix_experiments_dataset_id'), 'experiments', ['dataset_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=True),
    sa.Column('job_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('current_epoch', sa.Integer(), nullable=True),
    sa.Column('total_epoch', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('current_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_jobs_dataset_id_datasets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_jobs_experiment_id_experiments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_jobs_worker_id_workers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('experiment_id', 'job_name', name='uq_jobs_experiment_job_name')
    )
    op.create_index('ix_jobs_claim_order', 'jobs', ['status', 'priority', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_current_attempt_id'), 'jobs', ['current_attempt_id'], unique=False)
    op.create_index(op.f('ix_jobs_dataset_id'), 'jobs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_jobs_experiment_id'), 'jobs', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_worker_id'), 'jobs', ['worker_id'], unique=False)
    op.create_table('job_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('engine_mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_attempts_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_job_attempts_worker_id_workers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_attempts')),
    sa.UniqueConstraint('job_id', 'attempt_number', name='uq_job_attempt_number')
    )
    op.create_index(op.f('ix_job_attempts_job_id'), 'job_attempts', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_attempts_worker_id'), 'job_attempts', ['worker_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_uri', sa.String(length=2048), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['job_attempts.id'], name=op.f('fk_artifacts_attempt_id_job_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_artifacts_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts')),
    sa.UniqueConstraint('attempt_id', 'artifact_type', 'sha256', name='uq_artifact_attempt_type_sha')
    )
    op.create_index(op.f('ix_artifacts_artifact_type'), 'artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_artifacts_attempt_id'), 'artifacts', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_artifacts_job_id'), 'artifacts', ['job_id'], unique=False)
    op.create_table('ingest_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('batch_type', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['job_attempts.id'], name=op.f('fk_ingest_batches_attempt_id_job_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_ingest_batches_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_batches')),
    sa.UniqueConstraint('attempt_id', 'batch_type', 'idempotency_key', name='uq_ingest_batch_key')
    )
    op.create_index(op.f('ix_ingest_batches_attempt_id'), 'ingest_batches', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_ingest_batches_job_id'), 'ingest_batches', ['job_id'], unique=False)
    op.create_table('job_leases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_renewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['job_attempts.id'], name=op.f('fk_job_leases_attempt_id_job_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_leases_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_job_leases_worker_id_workers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_leases'))
    )
    op.create_index('ix_job_leases_active_expiry', 'job_leases', ['active', 'expires_at'], unique=False)
    op.create_index(op.f('ix_job_leases_attempt_id'), 'job_leases', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_job_leases_job_id'), 'job_leases', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_leases_worker_id'), 'job_leases', ['worker_id'], unique=False)
    op.create_table('job_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('fields_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['job_attempts.id'], name=op.f('fk_job_logs_attempt_id_job_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_logs_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_logs')),
    sa.UniqueConstraint('attempt_id', 'sequence', name='uq_job_log_attempt_sequence')
    )
    op.create_index(op.f('ix_job_logs_attempt_id'), 'job_logs', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_job_logs_job_id'), 'job_logs', ['job_id'], unique=False)
    op.create_table('job_status_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=True),
    sa.Column('previous_status', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['job_attempts.id'], name=op.f('fk_job_status_events_attempt_id_job_attempts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_status_events_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_status_events'))
    )
    op.create_index(op.f('ix_job_status_events_attempt_id'), 'job_status_events', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_job_status_events_job_id'), 'job_status_events', ['job_id'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=True),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['job_attempts.id'], name=op.f('fk_metrics_attempt_id_job_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_metrics_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics')),
    sa.UniqueConstraint('attempt_id', 'sequence', name='uq_metric_attempt_sequence')
    )
    op.create_index(op.f('ix_metrics_attempt_id'), 'metrics', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_metrics_job_id'), 'metrics', ['job_id'], unique=False)
    op.create_index(op.f('ix_metrics_key'), 'metrics', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_key'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_job_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_attempt_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_job_status_events_job_id'), table_name='job_status_events')
    op.drop_index(op.f('ix_job_status_events_attempt_id'), table_name='job_status_events')
    op.drop_table('job_status_events')
    op.drop_index(op.f('ix_job_logs_job_id'), table_name='job_logs')
    op.drop_index(op.f('ix_job_logs_attempt_id'), table_name='job_logs')
    op.drop_table('job_logs')
    op.drop_index(op.f('ix_job_leases_worker_id'), table_name='job_leases')
    op.drop_index(op.f('ix_job_leases_job_id'), table_name='job_leases')
    op.drop_index(op.f('ix_job_leases_attempt_id'), table_name='job_leases')
    op.drop_index('ix_job_leases_active_expiry', table_name='job_leases')
    op.drop_table('job_leases')
    op.drop_index(op.f('ix_ingest_batches_job_id'), table_name='ingest_batches')
    op.drop_index(op.f('ix_ingest_batches_attempt_id'), table_name='ingest_batches')
    op.drop_table('ingest_batches')
    op.drop_index(op.f('ix_artifacts_job_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_attempt_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_artifact_type'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_job_attempts_worker_id'), table_name='job_attempts')
    op.drop_index(op.f('ix_job_attempts_job_id'), table_name='job_attempts')
    op.drop_table('job_attempts')
    op.drop_index(op.f('ix_jobs_worker_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_experiment_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_dataset_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_current_attempt_id'), table_name='jobs')
    op.drop_index('ix_jobs_claim_order', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_experiments_dataset_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_workers_status'), table_name='workers')
    op.drop_index(op.f('ix_workers_current_job_id'), table_name='workers')
    op.drop_table('workers')
    op.drop_table('users')
    op.drop_index(op.f('ix_audit_events_resource_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
