import type {
  DatasetSummary,
  ExperimentSummary,
  JobSummary,
  WorkerSummary,
} from "./types";

export const demoWorkers: WorkerSummary[] = [
  {
    id: "worker-01",
    name: "gpu-seoul-01",
    status: "busy",
    engineMode: "fake",
    gpuName: "NVIDIA RTX 4090",
    vramUsedGb: 19.2,
    vramTotalGb: 24,
    gpuUtilization: 92,
    temperatureC: 68,
    currentJob: "speaker-a-v2-40k-e80",
    tags: ["nvidia", "24gb", "rmvpe"],
    workerVersion: "0.1.0",
    rvcCommit: "profile-pending",
    rvcAssetsReady: false,
    lastHeartbeat: "방금 전",
  },
  {
    id: "worker-02",
    name: "gpu-seoul-02",
    status: "online",
    engineMode: "fake",
    gpuName: "NVIDIA RTX 3090",
    vramUsedGb: 1.1,
    vramTotalGb: 24,
    gpuUtilization: 3,
    temperatureC: 41,
    currentJob: null,
    tags: ["nvidia", "24gb"],
    workerVersion: "0.1.0",
    rvcCommit: "profile-pending",
    rvcAssetsReady: false,
    lastHeartbeat: "4초 전",
  },
  {
    id: "worker-03",
    name: "gpu-busan-01",
    status: "offline",
    engineMode: "fake",
    gpuName: "NVIDIA A5000",
    vramUsedGb: 0,
    vramTotalGb: 24,
    gpuUtilization: 0,
    temperatureC: 0,
    currentJob: null,
    tags: ["nvidia", "24gb", "remote"],
    workerVersion: "0.0.9",
    rvcCommit: "unknown",
    rvcAssetsReady: false,
    lastHeartbeat: "18분 전",
  },
];

export const demoJobs: JobSummary[] = [
  {
    id: "job-001",
    name: "speaker-a-v2-40k-e80",
    experiment: "speaker-a-comparison-001",
    status: "training",
    worker: "gpu-seoul-01",
    version: "v2",
    sampleRate: "40k",
    f0Method: "rmvpe_gpu",
    currentEpoch: 47,
    totalEpoch: 80,
    latestLoss: 3.184,
    duration: "1시간 12분",
    engineMode: "fake",
    hasModel: false,
    hasIndex: false,
    hasSamples: false,
  },
  {
    id: "job-002",
    name: "speaker-a-v2-48k-e80",
    experiment: "speaker-a-comparison-001",
    status: "queued",
    worker: null,
    version: "v2",
    sampleRate: "48k",
    f0Method: "rmvpe_gpu",
    currentEpoch: 0,
    totalEpoch: 80,
    latestLoss: null,
    duration: "—",
    engineMode: "fake",
    hasModel: false,
    hasIndex: false,
    hasSamples: false,
  },
  {
    id: "job-003",
    name: "speaker-b-v1-40k-e100",
    experiment: "speaker-b-baseline",
    status: "completed",
    worker: "gpu-seoul-02",
    version: "v1",
    sampleRate: "40k",
    f0Method: "harvest",
    currentEpoch: 100,
    totalEpoch: 100,
    latestLoss: 2.921,
    duration: "2시간 41분",
    engineMode: "fake",
    hasModel: true,
    hasIndex: true,
    hasSamples: true,
  },
  {
    id: "job-004",
    name: "speaker-c-v2-40k-e60",
    experiment: "speaker-c-fast-test",
    status: "failed",
    worker: "gpu-busan-01",
    version: "v2",
    sampleRate: "40k",
    f0Method: "rmvpe_gpu",
    currentEpoch: 12,
    totalEpoch: 60,
    latestLoss: 4.102,
    duration: "22분",
    engineMode: "fake",
    hasModel: false,
    hasIndex: false,
    hasSamples: false,
  },
];

export const demoDatasets: DatasetSummary[] = [
  {
    id: "dataset-001",
    name: "speaker-a-clean-v1",
    status: "ready",
    isUsable: true,
    originalFilename: "speaker-a-clean-v1.zip",
    originalSizeBytes: null,
    originalSha256: null,
    originalMimeType: "application/zip",
    preparedFlatSizeBytes: null,
    preparedFlatSha256: null,
    manifestSha256: null,
    qualityReportSha256: null,
    durationMinutes: 38.4,
    fileCount: 184,
    sampleRate: "48 kHz",
    decoderPendingCount: 0,
    sourceFileEntries: 187,
    skippedCount: 2,
    rejectedCount: 0,
    duplicateCount: 1,
    pcmQuality: {
      algorithm: "pcm-sample-weighted-v1",
      validatedFileCount: 184,
      sampleCount: 110_592_000,
      clippingRatio: 0.001,
      silenceRatio: 0.08,
      rmsRatio: 0.18,
      silenceThresholdDbfs: -50,
      loudness: null,
    },
    failureCode: null,
    retryable: false,
    createdAt: "2026-07-11",
    updatedAt: "7월 11일 오후 03:00",
  },
  {
    id: "dataset-002",
    name: "speaker-b-studio-v2",
    status: "ready",
    isUsable: true,
    originalFilename: "speaker-b-studio-v2.zip",
    originalSizeBytes: null,
    originalSha256: null,
    originalMimeType: "application/zip",
    preparedFlatSizeBytes: null,
    preparedFlatSha256: null,
    manifestSha256: null,
    qualityReportSha256: null,
    durationMinutes: 22.7,
    fileCount: 96,
    sampleRate: "44.1 kHz",
    decoderPendingCount: 0,
    sourceFileEntries: 101,
    skippedCount: 3,
    rejectedCount: 1,
    duplicateCount: 1,
    pcmQuality: {
      algorithm: "pcm-sample-weighted-v1",
      validatedFileCount: 96,
      sampleCount: 60_064_200,
      clippingRatio: 0.004,
      silenceRatio: 0.12,
      rmsRatio: 0.14,
      silenceThresholdDbfs: -50,
      loudness: null,
    },
    failureCode: null,
    retryable: false,
    createdAt: "2026-07-10",
    updatedAt: "7월 10일 오후 08:12",
  },
  {
    id: "dataset-003",
    name: "speaker-c-upload",
    status: "processing",
    isUsable: false,
    originalFilename: "speaker-c-upload.zip",
    originalSizeBytes: null,
    originalSha256: null,
    originalMimeType: "application/zip",
    preparedFlatSizeBytes: null,
    preparedFlatSha256: null,
    manifestSha256: null,
    qualityReportSha256: null,
    durationMinutes: 0,
    fileCount: 312,
    sampleRate: "분석 중",
    decoderPendingCount: 0,
    sourceFileEntries: null,
    skippedCount: null,
    rejectedCount: null,
    duplicateCount: null,
    pcmQuality: null,
    failureCode: null,
    retryable: false,
    createdAt: "2026-07-11",
    updatedAt: "7월 11일 오후 03:05",
  },
];

export const demoExperiments: ExperimentSummary[] = [
  {
    id: "exp-001",
    name: "speaker-a-comparison-001",
    datasetName: "speaker-a-clean-v1",
    runCount: 3,
    completedCount: 1,
    bestRun: "speaker-a-v2-40k-e80",
    updatedAt: "3분 전",
  },
  {
    id: "exp-002",
    name: "speaker-b-baseline",
    datasetName: "speaker-b-studio-v2",
    runCount: 2,
    completedCount: 2,
    bestRun: "speaker-b-v1-40k-e100",
    updatedAt: "어제",
  },
];
